#ifndef LANEAPP_SECOND_SCREEN_LV_CONF_H
#define LANEAPP_SECOND_SCREEN_LV_CONF_H

#define LV_COLOR_DEPTH 32
#define LV_USE_STDLIB_MALLOC LV_STDLIB_CLIB
#define LV_USE_STDLIB_STRING LV_STDLIB_CLIB
#define LV_USE_STDLIB_SPRINTF LV_STDLIB_CLIB
#define LV_MEM_SIZE (32U * 1024U * 1024U)
#define LV_DEF_REFR_PERIOD 16
#define LV_DPI_DEF 130

#ifdef _WIN32
#define LV_USE_OS LV_OS_WINDOWS
#define LV_USE_WINDOWS 1
#define LV_USE_LINUX_FBDEV 0
#define LV_USE_EVDEV 0
#else
#define LV_USE_OS LV_OS_NONE
#define LV_USE_WINDOWS 0
#define LV_USE_LINUX_FBDEV 1
#define LV_LINUX_FBDEV_RENDER_MODE LV_DISPLAY_RENDER_MODE_PARTIAL
#define LV_LINUX_FBDEV_BUFFER_COUNT 2
#define LV_LINUX_FBDEV_BUFFER_SIZE 60
/* 副屏自有驱动需要对同一个输入 fd 执行 EVIOCGRAB，不能使用无独占接口的通用 evdev 驱动。 */
#define LV_USE_EVDEV 0
#endif

#define LV_USE_LOG 1
#define LV_LOG_LEVEL LV_LOG_LEVEL_WARN
#define LV_USE_ASSERT_NULL 1
#define LV_USE_ASSERT_MALLOC 1
#define LV_USE_ASSERT_STYLE 0

#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_20 1
#define LV_FONT_DEFAULT &lv_font_montserrat_14
#define LV_USE_TINY_TTF 1
#define LV_TINY_TTF_FILE_SUPPORT 1
#define LV_TINY_TTF_CACHE_GLYPH_CNT 512
#define LV_USE_FS_STDIO 1
#define LV_FS_STDIO_LETTER 'A'
#define LV_FS_STDIO_PATH ""
#define LV_FS_STDIO_CACHE_SIZE 4096

#define LV_USE_QRCODE 1
/* 当前运营界面不使用 SVG/Lottie，关闭 ThorVG 以缩短桌面端构建并减小产物。 */
#define LV_USE_LOTTIE 0
#define LV_USE_VECTOR_GRAPHIC 0
#define LV_USE_THORVG_INTERNAL 0
#define LV_USE_THORVG_EXTERNAL 0
#define LV_USE_SVG 0
#define LV_USE_SVG_ANIMATION 0
#define LV_USE_SVG_DEBUG 0
#define LV_USE_LODEPNG 0
#define LV_USE_BMP 0
#define LV_USE_GIF 0
#define LV_USE_JPG 0
#define LV_USE_FREETYPE 0
#define LV_BUILD_EXAMPLES 0
#define LV_BUILD_DEMOS 0

#endif
